[package]
name = "Rust_Homomorphic_Operations_Using_TFHE"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "x86_64"] }
rayon = "1.5"
num = "0.4"
